development:
    dialect: sqlite3
    datasource: development.db
    dir: migrations

# production:
#     dialect: postgres
#     datasource: dbname=myapp sslmode=disable
#     dir: migrations
#     table: migrations
