version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - "3336:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: funho_development
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
